AWSTemplateFormatVersion: "2010-09-09"
Description: Create IAM Role with inline policy

Resources:
  MyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: somesh-MyEC2Role
      AssumeRolePolicyDocument:   
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com   
            Action: sts:AssumeRole
      Policies:                   
        - PolicyName: somesh-MyEC2Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - ec2:Describe*
                  - s3:PutObject
                Resource: "*"      
